# Generated by Django 4.1 on 2022-08-11 20:31

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.TextField(default="No Subject")),
                ("message_body", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "file_data",
                    models.FileField(blank=True, null=True, upload_to="rms_files/"),
                ),
                ("date_of_creation", models.DateField(auto_now_add=True)),
                (
                    "coming_from",
                    models.CharField(
                        blank=True,
                        choices=[("website", "website"), ("erp", "erp")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("add_to_recyle_bin", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
