# Generated by Django 4.1 on 2022-08-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app7_rms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rms",
            name="is_stared",
            field=models.BooleanField(default=False),
        ),
    ]
