# Generated by Django 4.0.6 on 2022-08-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app6_master', '0003_itemcode'),
        ('app4_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app6_master.itemcode'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app6_master.unit'),
        ),
    ]
