# Generated by Django 4.0.6 on 2022-08-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4_product', '0002_product_item_code_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku_start',
        ),
    ]
