# Generated by Django 4.0.6 on 2022-07-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_employee_management', '0002_employee_profile_pic_alter_employee_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_leaving',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
