# Generated by Django 4.0.6 on 2022-07-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app3_employee_management', '0003_alter_employee_date_of_joining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_data', models.FileField(blank=True, null=True, upload_to='employee_documents/')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app3_employee_management.employee')),
            ],
        ),
    ]
