# Generated by Django 4.0.6 on 2022-08-07 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app6_master', '0003_itemcode'),
        ('app3_employee_management', '0005_employee_designation_employee_locker_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app6_master.designation'),
        ),
    ]
