# Generated by Django 4.0.6 on 2022-08-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app6_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
