# Generated by Django 4.0.6 on 2022-07-29 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1_authentication', '0002_remove_user_permissions_remove_user_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerissionAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('accounts', 'accounts'), ('product', 'product')], max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserPermissions',
        ),
    ]
