# Generated by Django 4.0.6 on 2022-07-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_authentication', '0003_perissionassign_delete_userpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perissionassign',
            name='name',
            field=models.CharField(blank=True, choices=[('accounts', 'accounts'), ('product', 'product'), ('employee_manage', 'employee_manage')], max_length=255, null=True),
        ),
    ]
